name: Build Aria2
on: push
jobs:
  build-static:
    runs-on: ubuntu-latest
    steps:
    - name: Install packages
      run: sudo apt-get install -y build-essential pkg-config cmake curl file
    - name: Download and build SQLite
      run: |
        curl https://www.sqlite.org/2019/sqlite-autoconf-3300100.tar.gz -svL | gzip -d - > sqlite-autoconf-3300100.tar
        tar xf sqlite-autoconf-3300100.tar
        cd sqlite-autoconf-3300100
        ./configure --prefix=$GITHUB_WORKSPACE
        make install
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: libsqlite3.a
        path: $GITHUB_WORKSPACE/lib/libsqlite3.a